# Generated by Django 5.1.2 on 2025-12-01 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('series', models.CharField(default='1', max_length=10, verbose_name='Série')),
                ('invoice_type', models.CharField(choices=[('nfe', 'NF-e - Nota Fiscal Eletrônica'), ('nfse', 'NFS-e - Nota Fiscal de Serviço'), ('nfce', 'NFC-e - Nota Fiscal ao Consumidor')], default='nfe', max_length=10)),
                ('access_key', models.CharField(blank=True, max_length=44, null=True, unique=True, verbose_name='Chave de Acesso')),
                ('issuer_name', models.CharField(max_length=200, verbose_name='Emitente')),
                ('issuer_tax_id', models.CharField(max_length=20, verbose_name='CNPJ Emitente')),
                ('issue_date', models.DateTimeField(verbose_name='Data de Emissão')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('authorization_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Autorização')),
                ('total_products', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de Produtos')),
                ('total_services', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de Serviços')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Desconto')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Frete')),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Seguro')),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Outras Despesas')),
                ('icms_base', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Base ICMS')),
                ('icms_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor ICMS')),
                ('ipi_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor IPI')),
                ('pis_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor PIS')),
                ('cofins_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor COFINS')),
                ('iss_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor ISS')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('authorized', 'Autorizada'), ('cancelled', 'Cancelada'), ('denied', 'Denegada')], default='draft', max_length=20)),
                ('protocol', models.CharField(blank=True, max_length=50, null=True, verbose_name='Protocolo')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='invoices/xml/%Y/%m/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-issue_date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Produto'), ('service', 'Serviço')], default='product', max_length=10)),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('ncm', models.CharField(blank=True, max_length=10, null=True, verbose_name='NCM')),
                ('cfop', models.CharField(max_length=10, verbose_name='CFOP')),
                ('unit', models.CharField(max_length=10, verbose_name='Unidade')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantidade')),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Unitário')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Desconto')),
                ('icms_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota ICMS')),
                ('icms_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor ICMS')),
                ('ipi_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota IPI')),
                ('ipi_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor IPI')),
                ('pis_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota PIS')),
                ('pis_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor PIS')),
                ('cofins_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota COFINS')),
                ('cofins_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor COFINS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Item da Nota Fiscal',
                'verbose_name_plural': 'Itens das Notas Fiscais',
            },
        ),
    ]
