# Generated by Django 5.1.2 on 2025-12-02 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_farm'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cfop',
            field=models.CharField(default='5101', max_length=4, verbose_name='CFOP'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço Emitente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Município Emitente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_city_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Código Município Emitente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro Emitente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_fantasy_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia Emitente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Emitente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Emitente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Emitente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_state_registration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual Emitente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP Emitente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='model_code',
            field=models.CharField(default='55', max_length=2, verbose_name='Código do Modelo'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='operation_nature',
            field=models.CharField(choices=[('venda_producao', 'Venda de produção do estabelecimento'), ('venda_mercadoria', 'Venda de mercadoria adquirida/recebida de terceiros'), ('venda_soja', 'Venda de Soja'), ('prestacao_servico', 'Prestação de serviço'), ('devolucao', 'Devolução de mercadoria'), ('transferencia', 'Transferência'), ('remessa', 'Remessa'), ('outras', 'Outras')], default='venda_producao', max_length=60, verbose_name='Natureza da Operação'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='operation_type',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='saida', max_length=10, verbose_name='Tipo de Operação'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço Destinatário'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Município Destinatário'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_city_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Código Município Destinatário'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro Destinatário'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Destinatário'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nome/Razão Social do Destinatário'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Destinatário'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Destinatário'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Destinatário'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_state_registration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual Destinatário'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_tax_id',
            field=models.CharField(default='', max_length=20, verbose_name='CNPJ/CPF Destinatário'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP Destinatário'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='Cliente/Destinatário'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issuer_name',
            field=models.CharField(max_length=200, verbose_name='Nome/Razão Social do Emitente'),
        ),
    ]
