# Generated by Django 5.1.2 on 2025-12-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_add_sefaz_pr_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='icms_origin',
            field=models.CharField(default='0', help_text='0=Nacional, 1=Estrangeira Importação direta, 2=Estrangeira Mercado interno, etc.', max_length=1, verbose_name='Origem da Mercadoria'),
        ),
    ]
