# Generated by Django 5.1.2 on 2025-12-02 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_farm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('account_type', models.CharField(choices=[('checking', 'Conta Corrente'), ('savings', 'Poupança'), ('investment', 'Investimento'), ('cash', 'Dinheiro')], max_length=20, verbose_name='Tipo')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('agency', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Conta')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Atual')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category_type', models.CharField(choices=[('revenue', 'Receita'), ('expense', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Inicial')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Receitas')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Despesas')),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Final')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fluxo de Caixa',
                'verbose_name_plural': 'Fluxo de Caixa',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('revenue', 'Receita'), ('expense', 'Despesa'), ('transfer', 'Transferência')], max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Desconto')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Juros')),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Multa')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Final')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('competence_date', models.DateField(verbose_name='Data de Competência')),
                ('payment_method', models.CharField(blank=True, choices=[('money', 'Dinheiro'), ('debit_card', 'Cartão de Débito'), ('credit_card', 'Cartão de Crédito'), ('bank_transfer', 'Transferência Bancária'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('check', 'Cheque'), ('other', 'Outro')], max_length=20, null=True, verbose_name='Forma de Pagamento')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('received', 'Recebido'), ('cancelled', 'Cancelado'), ('overdue', 'Vencido')], default='pending', max_length=20)),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Recorrente')),
                ('recurrence_frequency', models.CharField(blank=True, max_length=20, null=True, verbose_name='Frequência')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='financial/attachments/%Y/%m/', verbose_name='Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='financial.bankaccount', verbose_name='Conta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='financial.financialcategory', verbose_name='Categoria')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='financial.bankaccount', verbose_name='Conta Destino')),
            ],
            options={
                'verbose_name': 'Transação Financeira',
                'verbose_name_plural': 'Transações Financeiras',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Nota')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='clients.client')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receivable', to='financial.financialtransaction')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
            },
        ),
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Fornecedor')),
                ('supplier_tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ Fornecedor')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payable', to='financial.financialtransaction')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
    ]
