# Generated by Django 5.1.2 on 2025-12-01 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('oab_number', models.CharField(max_length=50, verbose_name='Número OAB')),
                ('oab_state', models.CharField(max_length=2, verbose_name='Estado OAB')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Advogado',
                'verbose_name_plural': 'Advogados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Número do Contrato')),
                ('contract_type', models.CharField(choices=[('service', 'Prestação de Serviço'), ('partnership', 'Parceria'), ('rental', 'Locação'), ('purchase', 'Compra e Venda'), ('confidentiality', 'Confidencialidade'), ('employment', 'Trabalho'), ('other', 'Outro')], max_length=50, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('counterpart', models.CharField(max_length=200, verbose_name='Outra Parte')),
                ('counterpart_tax_id', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ Outra Parte')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Contrato')),
                ('status', models.CharField(choices=[('draft', 'Minuta'), ('under_review', 'Em Análise'), ('active', 'Vigente'), ('expired', 'Expirado'), ('terminated', 'Rescindido')], default='draft', max_length=50, verbose_name='Status')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Arquivo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_contracts', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LegalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.CharField(max_length=100, unique=True, verbose_name='Número do Processo')),
                ('process_type', models.CharField(choices=[('civil', 'Cível'), ('labor', 'Trabalhista'), ('tax', 'Tributário'), ('corporate', 'Empresarial'), ('administrative', 'Administrativo'), ('other', 'Outro')], max_length=50, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('court', models.CharField(max_length=200, verbose_name='Comarca/Tribunal')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('suspended', 'Suspenso'), ('archived', 'Arquivado'), ('finished', 'Finalizado')], default='active', max_length=50, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridade')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('estimated_end_date', models.DateField(blank=True, null=True, verbose_name='Previsão de Término')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Estimado')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Real')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_processes', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legal_processes', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='legal.lawyer', verbose_name='Advogado')),
            ],
            options={
                'verbose_name': 'Processo Jurídico',
                'verbose_name_plural': 'Processos Jurídicos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LegalDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('overdue', 'Atrasado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_deadlines', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='legal.legalprocess', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Prazo Jurídico',
                'verbose_name_plural': 'Prazos Jurídicos',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_type', models.CharField(choices=[('conciliation', 'Conciliação'), ('instruction', 'Instrução'), ('judgment', 'Julgamento'), ('other', 'Outra')], max_length=50, verbose_name='Tipo')),
                ('date', models.DateTimeField(verbose_name='Data e Hora')),
                ('location', models.CharField(max_length=300, verbose_name='Local')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Realizada'), ('cancelled', 'Cancelada'), ('postponed', 'Adiada')], default='scheduled', max_length=20, verbose_name='Status')),
                ('result', models.TextField(blank=True, verbose_name='Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='legal.legalprocess', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Audiência',
                'verbose_name_plural': 'Audiências',
                'ordering': ['date'],
            },
        ),
    ]
